@startuml use_cases__registration
left to right direction
skinparam actorStyle Awesome
!theme bluegray
skinparam backgroundcolor White

'Titre'
title Use cases | Registration

'Acteur'
actor "Visitor" as Visiteur

'Rectangle'
rectangle {
    'Visiteur'
    "Fill in the form" as (RemplirFormulaire)
    "Send the form" as (EnvoyerFormulaire)   
    "Validate the registration email" as (ValiderMailInscription) 

    'Déroulement'
    :Visiteur: -.> (RemplirFormulaire)
    (RemplirFormulaire) -.> (EnvoyerFormulaire) : include
    (EnvoyerFormulaire) -.> (ValiderMailInscription) : include
}
@enduml