@startuml use_cases__delete_article
left to right direction
skinparam actorStyle Awesome
!theme bluegray
skinparam backgroundcolor White

'Titre'
title Use cases | Delete an article

'Acteur'
actor "Administrator" as Administrateur

'Rectangle'
rectangle {
    'Authentification'
    "«Authentication»" as (Authentification)

    'Administrateur'
    "Consult the articles dashboard" as (ConsulterTDBArticles)
    "Delete the article" as (SupprimerArticle)

    'Déroulement'
    :Administrateur: -.> (ConsulterTDBArticles)
    (ConsulterTDBArticles) -.> (SupprimerArticle) : include
    (SupprimerArticle) -.> (Authentification) : include
}
@enduml