@startuml use_cases__login
left to right direction
skinparam actorStyle Awesome
!theme bluegray
skinparam backgroundcolor White

'Titre'
title Use cases | Login

'Acteur'
actor "Visitor" as Visiteur

'Rectangle'
rectangle {
    'Authentification'
    "«Authentication»" as (Authentification)

    'Visiteur'
    "Fill in the form" as (RemplirFormulaire)
    "Send the form" as (EnvoyerFormulaire)    
    "Reset the password" as (OublierMDP)

    'Déroulement'
    :Visiteur: -.> (RemplirFormulaire)
    (RemplirFormulaire) -.> (EnvoyerFormulaire) : include
    (EnvoyerFormulaire) -.> (Authentification) : include
    :Visiteur: -.> (OublierMDP)
}
@enduml