@startuml sequence__edit_profil
hide footbox
skinparam actorStyle awesome
!theme aws-orange
skinparam backgroundcolor White

'Titre'
title Sequence | Edit profil

'Déroulement'
User -> System : Click on his profil
System --> User : Redirects to his profil
User -> System : Click on "Edit my profil"
System --> User : Redirects to the page of profil modifications
User -> System : Sends the form with the modifications
System -> System : Checks the form fields
System -> System : Replaces in the database the new information
System --> System : Disconnect the member
System -> User: Redirects to the login page with a message
@enduml