@startuml sequence__add_article
hide footbox
skinparam actorStyle awesome
!theme aws-orange
skinparam backgroundcolor White

'Titre'
title Sequence | Add an article

'Déroulement'
Administrator -> System : Click on "Create an article"
System --> Administrator : Redirects to the article creation page
Administrator -> Administrator : Fills in the form
Administrator -> System : Sends the request to publish the article
System -> System : Checks the form fields
System -> System : Saves the article in the database
System --> Administrator: Displays an action confirmation message
@enduml