@startuml sequence__change_role
hide footbox
skinparam actorStyle awesome
!theme aws-orange
skinparam backgroundcolor White

'Titre'
title Sequence | Change role

'Déroulement'
Administrator -> Administrator: View the member dashboard
Administrator -> Administrator: Selects a member and changes his role
Administrator -> System: Sends the modification
System -> System : Saves the modification in the database
System --> Administrator: Displays an action confirmation message
System -> User : Notify by mail that his role has changed
@enduml