@startuml use_cases__contact
left to right direction
skinparam actorStyle Awesome
!theme bluegray
skinparam backgroundcolor White

'Titre'
title Use cases | Contact

'Acteurs'
actor "Sender" as Expéditeur
actor "Administrator" as Administrateur
Expéditeur <|- Administrateur

'Rectangle'
rectangle {
    'Expéditeur'
    "Fill in the form" as (RemplirFormulaire)
    "Send the form" as (EnvoyerFormulaire)

    'Administrateur'
    "Receive the contact email(s)" as (RecevoirMail)
    "Reply to email(s)" as (RepondreMails)

    'Déroulement'
    :Expéditeur: -.> (RemplirFormulaire)
    (RemplirFormulaire) -.> (EnvoyerFormulaire) : include
    :Administrateur: -.> (RecevoirMail)
    (RecevoirMail) -.> (RepondreMails) : include
}
@enduml