@startuml use_cases__change_role
left to right direction
skinparam actorStyle Awesome
!theme bluegray
skinparam backgroundcolor White

'Titre'
title Use cases | Change role

'Acteur'
actor "Administrator" as Administrateur

'Rectangle'
rectangle {
    'Authentification'
    "«Authentication»" as (Authentification)

    'Administrateur'
    "Consult the members dashboard" as (ConsulterTDBMembres)
    "Change the role of the member" as (ModifierRole)

    'Déroulement'
    :Administrateur: -.> (ConsulterTDBMembres)
    (ConsulterTDBMembres) -.> (ModifierRole) : include
    (ModifierRole) -.> (Authentification) : include
}
@enduml