@startuml sequence__reset_password
hide footbox
skinparam actorStyle awesome
!theme aws-orange
skinparam backgroundcolor White

'Titre'
title Sequence | Reset the password

'Déroulement'
Visitor -> System : Click on "If you wish to reset your password, click here."
System --> Visitor : Send the user to a form
Visitor -> System : Send the form with his email address
System -> System: Checks if the member exists
System --> Visitor: Sends an email with a link to change his password
Visitor -> System: Sends the form with his new password
System -> System : Replace in the database with the new password
System --> Visitor : Display a confirmation message
System -> Visitor : Redirects to the login page
@enduml