@startuml sequence__contact
hide footbox
skinparam actorStyle awesome
!theme aws-orange
skinparam backgroundcolor White

'Titre'
title Sequence | Contact

'Déroulement'
Sender -> Sender : Fills in the contact form correctly
Sender -> System : Sends the contact form
System -> System : Checks the different values of the form
System --> Sender : Show a message to inform that the form has been sent
System -> Administrator : Sends an email containing the sender's information
Administrator -> Sender: Replies to the sender by mail
@enduml