@startuml use_cases__add_article
left to right direction
skinparam actorStyle Awesome
!theme bluegray
skinparam backgroundcolor White

'Titre'
title Use cases | Add article

'Acteur'
actor "Administrator" as Administrateur

'Rectangle'
rectangle {
    'Authentification'
    "«Authentication»" as (Authentification)

    'Administrateur'
    "Consult the article dashboard" as (ConsulterTDBArticles)
    "Create an article" as (CreerArticle)
    "Fill in the form" as (RemplirFormulaire)
    "Publish the article" as (PublierArticle)

    'Déroulement'
    :Administrateur: -.> (ConsulterTDBArticles)
    (ConsulterTDBArticles) -.> (CreerArticle) : include
    (CreerArticle) -.> (RemplirFormulaire) : include
    (RemplirFormulaire) -.> (PublierArticle) : include
    (PublierArticle) -.> (Authentification) : include
}
@enduml