@startuml sequence__add_comment
hide footbox
skinparam actorStyle awesome
!theme aws-orange
skinparam backgroundcolor White

'Titre'
title Sequence | Add a comment

'Déroulement'
User -> User : Fills in the form to add a comment
User -> System : Sends the comment form
System -> System : Checks the different values of the form
System -> System : Saves the comment in the database as pending
System --> User : Displays a message warning that the comment has been sent but that it must be verified
Administrator -> System : Go to his comments dashboard, and select the action
System -> System : Change the status of the comment to published in the database
System --> Administrator: Displays an action confirmation message
@enduml