@startuml sequence__registration
hide footbox
skinparam actorStyle awesome
!theme aws-orange
skinparam backgroundcolor White

'Titre'
title Sequence | Registration

'Déroulement'
Visitor -> Visitor : Fills in the registration form correctly
Visitor -> System: Sends the registration form
System -> System: Checks the different values of the form
System -> System: Registers the new member in the database
System --> Visitor: Sends an email containing a link to activate his account
Visitor -> System: Activate his account
System --> Visitor: Displays a confirmation message of action
@enduml