@startuml use_cases__edit_article
left to right direction
skinparam actorStyle Awesome
!theme bluegray
skinparam backgroundcolor White

'Titre'
title Use cases | Edit an article

'Acteur'
actor "Administrator" as Administrateur

'Rectangle'
rectangle {
    'Authentification'
    "«Authentication»" as (Authentification)

    'Administrateur'
    "Consult the article dashboard" as (ConsulterTDBArticles)
    "Edit the article" as (ModifierArticle)
    "Save the changes" as (EnregistrerModifications)

    'Déroulement'
    :Administrateur: -.> (ConsulterTDBArticles)
    (ConsulterTDBArticles) -.> (ModifierArticle) : include
    (ModifierArticle) -.> (EnregistrerModifications) : include
    (EnregistrerModifications) -.> (Authentification) : include
}
@enduml