@startuml sequence__delete_article
hide footbox
skinparam actorStyle awesome
!theme aws-orange
skinparam backgroundcolor White

'Titre'
title Sequence | Delete an article

'Déroulement'
Administrator -> Administrator : Select an article
Administrator -> System : Click on "Delete article"
System -> System : Delete the item from the database
System --> Administrator: Displays an action confirmation message
@enduml