@startuml use_cases__delete_account
left to right direction
skinparam actorStyle Awesome
!theme bluegray
skinparam backgroundcolor White

'Titre'
title Use cases | Delete account

'Acteur'
actor "Administrator" as Administrateur
actor "User" as User

'Rectangle'
rectangle {
    'Authentification'
    "«Authentication»" as (Authentification)

    'Administrateur'
    "Consult the members dashboard" as (ConsulterTDBMembres)
    "Click on delete" as (ClickSuppr)
    
    'User'
    "Click on his profil" as (GoProfil)
    "Click on delete" as (ClickSupprUser)
    "Validate the link" as (ValidateLink)

    'Déroulement'
    :Administrateur: -.> (ConsulterTDBMembres)
    :User: -.> (GoProfil)
    (ConsulterTDBMembres) -.> (ClickSuppr) : include
    (GoProfil) -.> (ClickSupprUser) : include
    (ClickSuppr) -.> (Authentification) : include
    (ClickSupprUser) -.> (ValidateLink) : include
    (ValidateLink) -.> (Authentification) : include
}
@enduml