@startuml use_cases__delete_account
left to right direction
skinparam actorStyle Awesome
!theme bluegray
skinparam backgroundcolor White

'Titre'
title Use cases | Delete account

'Acteur'
actor "Administrator" as Administrateur
actor "User" as User

'Rectangle'
rectangle {
    'Authentification'
    "«Authentication»" as (Authentification)

    'General'
    "Click on delete" as (ClickSuppr)
    "Save changes" as (EnregistrerModifications)

    'Administrateur'
    "Consult the members dashboard" as (ConsulterTDBMembres)
    
    'User'
    "Click on his profil" as (GoProfil)

    'Déroulement'
    :Administrateur: -.> (ConsulterTDBMembres)
    :User: -.> (GoProfil)
    (ConsulterTDBMembres) -.> (ClickSuppr) : include
    (GoProfil) -.> (ClickSuppr) : include
    (ClickSuppr) -.> (EnregistrerModifications) : include
    (EnregistrerModifications) -.> (Authentification) : include

}
@enduml