@startuml use_cases__edit_profile
left to right direction
skinparam actorStyle Awesome
!theme bluegray
skinparam backgroundcolor White

'Titre'
title Use cases | Edit profile

'Acteur'
actor "User" as Utilisateur

'Rectangle'
rectangle {
    'Authentification'
    "«Authentication»" as (Authentification)

    'Utilisateur'
    "Click on his profile" as (CliquerProfil)
    "Click on edit my profile" as (ModifierProfil)
    "Modify your information" as (ModifierInformations)
    "Save changes" as (EnregistrerModifications)

    'Déroulement'
    :Utilisateur: -.> (CliquerProfil)
    (CliquerProfil) -.> (ModifierProfil) : include
    (ModifierProfil) -.> (ModifierInformations) : include
    (ModifierInformations) -.> (EnregistrerModifications) : include
    (EnregistrerModifications) -.> (Authentification) : include
}
@enduml