@startuml sequence__edit_profile
hide footbox
skinparam actorStyle awesome
!theme aws-orange
skinparam backgroundcolor White

'Titre'
title Sequence | Edit profile

'Déroulement'
Visitor -> System : Click on his profile
System --> Visitor : Redirects to his profile
Visitor -> System : Click on "Edit my profile
System --> Visitor : Redirects to the page of profile modifications
Visitor -> System : Sends the form with the modifications
System -> System : Checks the form fields
System -> System : Replaces in the database the new information
System --> Visitor: Displays an action confirmation message
System -> Visitor: Redirects to profile page
@enduml